### ISSUE TITLE
Long error

### ISSUE THREAD

**Issue by patrickyan** [s-a/sublime-text-refactor#16]
When trying to do anything i get this error:

```
WARN: ERROR: Unexpected token: punc (,) [null:406,2]

/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199
    throw new JS_Parse_Error(message, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:185:18)
    at js_error (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199:11)
    at croak (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:630:9)
    at token_error (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:638:9)
    at unexpected (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:644:9)
    at /Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:724:17
    at /Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:677:24
    at block_ (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:938:20)
    at ctor.body (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:911:25)
    at function_ (/Users/Pat/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:916:15)
```

**Comment by granteagon** [comment]
I'm getting this error in ember-cli which uses ES6 syntax.

The line is:
```js
import Ember from 'ember';
```

Is there a solution for this?

**Comment by s-a** [comment]
Sorry there is no ES6 support for this plugin.

**Comment by s-a** [comment]
Just created a ticket for es6 feature request at #24
