### ISSUE TITLE
error when method extraction

### ISSUE THREAD

**Issue by deeperx** [s-a/sublime-text-refactor#28]
**In the below code, ```extract method``` refactoring fails:**

```javascript
      url = this.getServerUrl();
      tag = publisherTag = this.getTag();
      id = this.getPublisherId();
      
      if (id === 0) {
        return false;
      }

      if (!tag) {
        return false;
      }

      if (this.doOther(id)) {
        return false;
      }
```

**ERROR MESSAGE:**

```javascript
b"util.error: Use console.error instead
WARN: ERROR: 'return' outside of function [null:7,17]

/Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199
    throw new JS_Parse_Error(message, line, col, pos);
          ^
          Error
    at new JS_Parse_Error (/Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:185:18)
    at js_error (/Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199:11)
    at croak (/Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:634:41)
    at /Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:762:21
    at /Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:677:24
    at block_ (/Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:938:20)
    at /Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:714:29
    at /Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:677:24
    at if_ (/Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:921:44)
    at /Users/me/Library/Application Support/Sublime Text 3/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:758:24
    "
```

**Comment by deeperx** [comment]
Maybe, this is related with UglifyJS, there is an issue over there I think closely about this also: https://github.com/mishoo/UglifyJS2/issues/288

They recommend adding when calling UglifyJS: 

```
There you go. Pass --bare-returns. The original behavior is still on by default.
```

**Comment by s-a** [comment]
Hi,
ty for reporting this. You can try the option at https://github.com/s-a/sublime-text-refactor/blob/master/js/parse.js#L37. I am currently too busy :bee:
