### ISSUE TITLE
Error (uglify related?) using any option in the Refactor context menu

### ISSUE THREAD

**Issue by Ramarti** [s-a/sublime-text-refactor#30]
Hi!

First of all thanks for getting this out, looks awesome! Sadly I can't make it work, every option on the Refactor context menu pops up this message:

```
(node) util.error is deprecated. Use console.error instead.
WARN: ERROR: Unexpected token: name (strict) [null:7,4]

/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199
    throw new JS_Parse_Error(message, line, col, pos);
    ^
Error
    at new JS_Parse_Error (/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:185:18)
    at js_error (/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:199:11)
    at croak (/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:630:9)
    at token_error (/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:638:9)
    at unexpected (/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:644:9)
    at semicolon (/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:664:43)
    at simple_statement (/Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:822:73)
    at /Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:707:19
    at /Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:677:24
    at /Users/raulmartinezfernandez/Library/Application Support/Sublime Text 2/Packages/JavaScript Refactor/js/node_modules/uglify-js/lib/parse.js:1395:23
```

I'm using Sublime Text 2, Version 2.0.2, Build 2221 on OSX El Capitan 10.11.1

Lookinf forward to use this plugin :)

**Comment by s-a** [comment]
This indicates a javascript error. Can you please send a reproducable code sample?
