### ISSUE TITLE
b'/bin/sh: node: command not found\n'

### ISSUE THREAD

**Issue by hced** [s-a/sublime-text-refactor#7]
(I'm using Sublime Text 3 (3033) on Mac and Node v0.10.9.)

Example JS file:

```
#!/usr/bin env node

var fromNum = 0;
var toNum = 10;

var numRange = [];

for (var i = fromNum; i < toNum; i++) {
    numRange.push(i);
}

for (var i = 0; i < numRange.length; i++) {
    console.log(numRange[i]);
}
```

Double-clicking/selecting `numRange` in this case, then right-clicking and selecting `Refactor > Rename` results in the following. (Note: the same result occur when doing any other action except for the selection commands which seems to work.)

A popup dialog saying:

```
b'/bin/sh: node: command not found\n'
```

And the following output in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/hced/Dropbox/Henrik/Application Support/Sublime Text 3/Installed Packages/JavaScript Refactor.sublime-package/Refactor.py", line 151, in run
  File "/Users/hced/Dropbox/Henrik/Application Support/Sublime Text 3/Installed Packages/JavaScript Refactor.sublime-package/Refactor.py", line 161, in RenamevariableCommand
  File "/Users/hced/Dropbox/Henrik/Application Support/Sublime Text 3/Installed Packages/JavaScript Refactor.sublime-package/Refactor.py", line 37, in executeNodeJsShell
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by jonashackt** [comment]
Thanks @JohnTheDaniel, @s-a and @byterider. All the hints together worked for me on Yosemite. 

Maybe for others it would be helpful to mention, that the path to "node" needs to be set, because nodejs is needed - which is not installed by default on your Mac, but could be easily installed by downloading and installing it from the [nodejs-Website](http://nodejs.org/) or even more faster with [homebrew](http://brew.sh/) (brew install node).

**Comment by JedatKinports** [comment]
@byterider thanks! This solved it for me as well on macOS Sierra:

"(right click)" -> "Refactor" -> "Preferences: Refactor Settings - User" -> and i added this:

{
    "nodePath" : "/usr/local/bin/node"
}
